// Code generated by tools/gerar-tabela-diacriticos. DO NOT EDIT.
//
// Regenerar:
//
//	cargo build --release --manifest-path tools/gerar-tabela-diacriticos/dump/Cargo.toml
//	tools/gerar-tabela-diacriticos/dump/target/release/dump-unicode > /tmp/unicode.tsv
//	go run ./tools/gerar-tabela-diacriticos /tmp/unicode.tsv
package pdftext

// excecoesDePalavra são as runas em que o `\w` Unicode do crate `regex`,
// usado na junção de hífens do legado, diverge da aproximação nativa em Go.
//
// O `\w` do Rust é [\p{Alphabetic}\p{M}\p{Nd}\p{Pc}\p{Join_Control}]. Duas
// diferenças custaram divergência real, encontradas pelo teste de propriedade
// da fase F6 (INV-P02):
//
//   - INCLUI marcas combinantes: "6" seguido de U+0327 antes de "-\n" JUNTA no
//     legado;
//   - EXCLUI as categorias No e Nl: "¼" antes de "-\n" NÃO junta, embora
//     `\p{N}` do Go as inclua.
//
// O valor é o que o RUST decide.
//
// Gerada por comparação runa a runa de todo o plano básico multilíngue,
// perguntando ao próprio motor de expressões regulares do Rust.
var excecoesDePalavra = map[rune]bool{
	0x0897: true, // U+0897 ?
	0x1C89: true, // U+1C89 ?
	0x1C8A: true, // U+1C8A ?
	0xA7CB: true, // U+A7CB ?
	0xA7CC: true, // U+A7CC ?
	0xA7CD: true, // U+A7CD ?
	0xA7DA: true, // U+A7DA ?
	0xA7DB: true, // U+A7DB ?
	0xA7DC: true, // U+A7DC ?
}
